### ISSUE TITLE
i cant run plz help and i dont want to go into 1.16 

### ISSUE THREAD

**Issue by Dr-krumpet** [BiggerSeries/BiggerReactors#48]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 25/04/2022, 19:13
Description: Quartz failed to startup

java.lang.NoSuchMethodError: 'void net.roguelogix.phosphophyllite.config.ConfigManager.registerConfig(java.lang.reflect.Field, java.lang.String)'
	at net.roguelogix.quartz.QuartzConfig.<clinit>(QuartzConfig.java:21) ~[quartz-1.18.2-0.0.0-beta.1.1.jar%2359!/:0.0.0-beta.1.1] {re:classloading}
	at net.roguelogix.quartz.internal.QuartzCore.<clinit>(QuartzCore.java:36) ~[quartz-1.18.2-0.0.0-beta.1.1.jar%2359!/:0.0.0-beta.1.1] {re:mixin,re:classloading}
	at net.roguelogix.quartz.internal.EventListener.<clinit>(EventListener.java:28) ~[quartz-1.18.2-0.0.0-beta.1.1.jar%2359!/:0.0.0-beta.1.1] {re:mixin,re:classloading}
	at com.mojang.blaze3d.platform.Window.handler$zdg000$startQuartz(Window.java:746) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:quartz.mixins.json:QuartzStartupMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:148) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:quartz.mixins.json:QuartzStartupMixin,pl:mixin:A}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.48.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 11.6.5
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 668002872 bytes (637 MiB) / 1073741824 bytes (1024 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 69 Stepping 1
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 1.30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 5000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0a26
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 6144.00
	Virtual memory used (MB): 3663.83
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 741.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 4

**Comment by RogueLogix** [comment]
add [Phosphophyllite](https://www.curseforge.com/minecraft/mc-mods/phosphophyllite/files/3735717), and remove optifine.
